version: 1.0.{build}
image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - cmd: dotnet restore ./src/TwentyTwenty.BaseLine/TwentyTwenty.BaseLine.csproj
build_script:
  - cmd: dotnet pack ./src/TwentyTwenty.BaseLine/TwentyTwenty.BaseLine.csproj --no-restore -c Release /p:SemVer=%GitVersion_NuGetVersion%
test: off
deploy:
  - provider: NuGet
    api_key:
      secure: 6LqavZsVwaAsuw6SK7XKQRuMzqb9pedzqVK7AI0+j3w51bN1FOu7Fi2l2Fj6bmu/
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: "%GitVersion_NuGetVersion%"
    description: 'TwentyTwenty.BaseLine'
    auth_token:
      secure: fd/+7iqe48Pb5+TSjRLgl4uEP4FvKjAv8xs0MI+cgYPJ3QX2/cBdfJt2E6fbwHFr
    artifact: /.*\.nupkg/
    draft: true
    on:    
      appveyor_repo_tag: true        # deploy on tag push only